/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// golf_glove_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_GOLF_GLOVE                                             0x3a, 0xc5, 0x98, 0xd6, 0x1b, 0x7e, 0x42, 0x2e, 0xb5, 0xf1, 0x34, 0xfe, 0x48, 0x89, 0x83, 0x7c
#define __UUID_GOLF_GLOVE_ACCELEROMETER_X__WRIST_                     0x71, 0x49, 0x60, 0xad, 0x75, 0x92, 0x4c, 0x7f, 0x98, 0x69, 0x1b, 0xfb, 0x9a, 0x06, 0x6f, 0xa8
#define __UUID_GOLF_GLOVE_ACCELEROMETER_Y__WRIST_                     0x8e, 0xbd, 0xf6, 0xcc, 0xc8, 0x4a, 0x4b, 0xf4, 0x80, 0x14, 0x95, 0xbd, 0xdc, 0x42, 0xb3, 0x97
#define __UUID_GOLF_GLOVE_ACCELEROMETER_Z__WRIST_                     0xca, 0xd2, 0x83, 0x84, 0x89, 0xbd, 0x47, 0x87, 0xbf, 0xe3, 0x40, 0x6e, 0x23, 0x45, 0x50, 0x73

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                                        0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                                           0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME                               0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE                         0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE                                0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE                          0x0018

// ***** Primary Service 'golf-glove'
#define HDLS_GOLF_GLOVE                                               0x0028
// ----- Characteristic 'Accelerometer X (Wrist)'
#define HDLC_GOLF_GLOVE_ACCELEROMETER_X__WRIST_                       0x0029
#define HDLC_GOLF_GLOVE_ACCELEROMETER_X__WRIST__VALUE                 0x002A
// ===== Descriptor 'Client Configuration'
#define HDLD_GOLF_GLOVE_ACCELEROMETER_X__WRIST__CLIENT_CONFIGURATION  0x002B
// ===== Descriptor 'Presentation Format'
#define HDLD_GOLF_GLOVE_ACCELEROMETER_X__WRIST__PRESENTATION_FORMAT_0 0x002C
// ----- Characteristic 'Accelerometer Y (Wrist)'
#define HDLC_GOLF_GLOVE_ACCELEROMETER_Y__WRIST_                       0x002D
#define HDLC_GOLF_GLOVE_ACCELEROMETER_Y__WRIST__VALUE                 0x002E
// ===== Descriptor 'Client Configuration'
#define HDLD_GOLF_GLOVE_ACCELEROMETER_Y__WRIST__CLIENT_CONFIGURATION  0x002F
// ===== Descriptor 'Presentation Format'
#define HDLD_GOLF_GLOVE_ACCELEROMETER_Y__WRIST__PRESENTATION_FORMAT_0 0x0030
// ----- Characteristic 'Accelerometer Z (Wrist)'
#define HDLC_GOLF_GLOVE_ACCELEROMETER_Z__WRIST_                       0x0031
#define HDLC_GOLF_GLOVE_ACCELEROMETER_Z__WRIST__VALUE                 0x0032
// ===== Descriptor 'Client Configuration'
#define HDLD_GOLF_GLOVE_ACCELEROMETER_Z__WRIST__CLIENT_CONFIGURATION  0x0033
// ===== Descriptor 'Presentation Format'
#define HDLD_GOLF_GLOVE_ACCELEROMETER_Z__WRIST__PRESENTATION_FORMAT_0 0x0034

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table golf_glove_gatt_db_ext_attr_tbl[];
extern const uint16_t golf_glove_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

#endif /* __GATT_DATABASE_H__ */
